### ISSUE TITLE
Implement OTA updates

### ISSUE THREAD

**Issue by jeffkowalski** [SOTAmat/SOTAcat#13]
Brian says:
OTA updates would be wonderful.  However, we are nearly at the 2MB limit and OTA requires 3X the storage.  We can double our memory because PlatformIO thinks our board only has 2MB of storage when in fact it has 4MB.  We need to twiddle a setting.

**Comment by jeffkowalski** [comment]
Just some background: https://blog.espressif.com/ota-updates-framework-ab5438e30c12

**Comment by brianmathews** [comment]
Note, I found the bug where our module was being sensed as only 2MB Flash, when in fact we have 4MB flash.
That issue was fixed in an earlier check-in.
So OTA is very much possible now that we have access to the full 4MB.

**Comment by jeffkowalski** [comment]
I think that was fixed in 923b60148b2fe55c2a9f7a633c6099469deb784d
I've been looking into OTA.
One thing to decide - does the user upload a .bin that they've downloaded from somewhere, or should we "check for updates" against a known URL?

**Comment by brianmathews** [comment]
I would check for updates against a known location such as the sotamat.com web server. GitHub LFS does not allow us to purge old versions and storage counts against the free tier quota.  Hence we should use some non-GitHub web server.

We also want to make the process as simple as possible for non-developers. Developers can build their own source from GitHub.

**Comment by jeffkowalski** [comment]
(Note to self, more background information) see https://gitlab.com/kevinwolfe/esp32_template/-/blob/87ca0ecd615115fdc33013d45b84a237da230575/main/main.c for example

**Comment by jeffkowalski** [comment]
@brianmathews Please give me a URL on sotamat.com where I can check for "official" releases of SOTAcat.  I'd like to implement the "check for new version" feature, which is a component of OTA updates.

**Comment by brianmathews** [comment]
You can name the file(s) anything you want.  They will just be part of the Wordpress Media folder as files in the pattern:

https://sotamat.com/wp-content/uploads/<YOUR-FILENAME-HERE>

**Comment by jeffkowalski** [comment]
Excellent.
What will be the protocol for:
1. Identifying release-able commit-points
2. Building the code 
3. Uploading and naming the file.  (who has access)
4. Updating the "latest.txt" at the same place, if we assume to go that route.
Can you envision a script for 2-4?  MakeRelease.sh?  ;)

**Comment by jeffkowalski** [comment]
We may want a different unified BIN that doesn't blow away settings in
NVS.  Maybe one that just packs code and web assets.  Different build
script?
