### ISSUE TITLE
Add drop-down option to select the time period recent spots are requested for

### ISSUE THREAD

**Issue by poynting** [SOTAmat/SOTAcat#22]
Enhancement.

Currently it's hard-coded to 1 hour; for testing during certain time periods it's nice to have it be longer, and in the field it may be nice to have it be shorter to only see very recent spots.

Maybe a drop down with a list of options:

`15m, 30m, 1h, 2h, 3h`

which just changes the duration on the web queries.

**Comment by jeffkowalski** [comment]
Reopening, due to comments in #38, which indicated I misinterpreted the original request in implementing a "polling rate".  Brian clarified that it's more useful to have an adjustable "lookback period".
