### ISSUE TITLE
Manage WiFi Credentials from web UI

### ISSUE THREAD

**Issue by poynting** [SOTAmat/SOTAcat#23]
We'll need users to be able to set the WiFi credentials for the network they want SOTAcat to connect to. This might be a home network or a phone/hotspot. Since the SOTAcat will serve an AP when it doesn't find a host WiFi to connect to, the user should be able to set their home WiFi credentials via the captive portal. 

We may want another issue to track for general user-defined preferences management, and implement this on top of that once it's in place.

**Comment by jeffkowalski** [comment]
Full preferences now implemented in https://github.com/SOTAmat/SOTAcat/commit/fb570e59f74094632f1362b9f68b0c3217aaf5b5
