### ISSUE TITLE
Show distance to SOTA Peak / POTA Park in "recent spots" table, allow sorting by distance

### ISSUE THREAD

**Issue by brianmathews** [SOTAmat/SOTAcat#4]
In the SOTACAT web site you can see a table of recent spots for SOTA or POTA.  Those tables show the spot Peak or Park.

This is a feature request for the ability to capture the user's current location from GPS (if the user provides permission to do so) and then compute the distance between the user and the Peak / Park shown in the recent spots table.  We can get the Latitude/Longitude information from the same SOTA/POTA servers that give us the recent spots list.

We can then display the distance in the SOTACAT tables, and potentially allow sorting by that column.

**Comment by jeffkowalski** [comment]
Partially addressed by ccd3839955e451c361f5fef2aa8ac1a8ffd76040, in that distances from current position to spots are shown.
Sorting will come in a different commit.
