### ISSUE TITLE
Nasty timeout bug between SOTAMAT and SOTACAT

### ISSUE THREAD

**Issue by jeffkowalski** [SOTAmat/SOTAcat#9]
Per Brian:  I think I need to debug this as it is likely in the Xamarin code.
Duplicate of #3?

**Comment by jeffkowalski** [comment]
@brianmathews, would you kindly comment on whether this is a dup of #3 ?

**Comment by brianmathews** [comment]
Yes. This is a duplicate of #3.
Closing.
